### Create a task
POST localhost:3000/tasks
Content-Type: application/json

{
  "title": "Test Task",
  "description": "Test Description"
}

> {% client.global.set('taskId', response.body.id) %}

### Get All Tasks
GET localhost:3000/tasks

### Get Task by Id
GET localhost:3000/tasks/{{taskId}}

### Delete Task by Id
DELETE localhost:3000/tasks/{{taskId}}

### Update Task Status by Id
PATCH localhost:3000/tasks/{{taskId}}/status
Content-Type: application/json

{
  "status": "IN_PROGRESS"
}