version: '3.0'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: data
    ports:
      - "5432:5432"
    restart: always
